trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  UNITY_VERSION: '2023.1.0f1' # Altere para a versão do Unity que você está usando
  UNITY_BUILD_TARGET: 'StandaloneWindows64' # Alvo do build
  PROJECT_PATH: '.' # Caminho do projeto Unity no repositório

steps:

# Restauração de pacotes do Unity
- script: |
    echo "Restaurando pacotes do Unity..."
    C:\\Program Files\\Unity\\Hub\\Editor\\$(UNITY_VERSION)\\Editor\\Unity.exe -projectPath $(PROJECT_PATH) -quit -batchmode -logfile -refresh-import
  displayName: 'Restaurar pacotes Unity'

# Build do jogo para Windows
- script: |
    echo "Iniciando build do Unity..."
    C:\\Program Files\\Unity\\Hub\\Editor\\$(UNITY_VERSION)\\Editor\\Unity.exe -projectPath $(PROJECT_PATH) -quit -batchmode -buildTarget $(UNITY_BUILD_TARGET) -logfile -executeMethod BuildScript.PerformBuild
  displayName: 'Build do jogo Unity'

# Publicação do artefato de build
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(PROJECT_PATH)/Build/StandaloneWindows64'
    artifactName: 'UnityWindowsBuild'
    publishLocation: 'Container'